<script src="<?= $this->getUrl('dist/bootstrap/js/bootstrap.min.js') ?>"></script>

<!-- iCheck -->
<script src="<?= $this->getUrl('dist/plugins/iCheck/icheck.min.js') ?>"></script>
<script src="<?= $this->getUrl('dist/js/formatCurrency.js') ?>"></script>
<script src="<?= $this->getUrl('dist/js/jquery.form.min.js') ?>"></script>
<script src="<?= $this->getUrl('dist/js/bootstrap-notify.min.js') ?>"></script>
<script src="<?= $this->getUrl('dist/plugins/pace/pace.min.js') ?>"></script>
<script src="<?= $this->getUrl('dist/plugins/select2/js/select2.full.js') ?>"></script>
<script src="<?= $this->getUrl('dist/plugins/select2/js/i18n/pt-BR.js') ?>"></script>
<script src="<?= $this->getUrl('dist/plugins/input-mask/jquery.inputmask.js') ?>"></script>
<script src="<?= $this->getUrl('dist/js/upload.js') ?>"></script>
<!-- AdminLTE App -->
<script src="<?= $this->getUrl('dist/js/adminlte.min.js') ?>"></script>
<script src="<?= $this->getUrl('dist/js/app.js') ?>"></script>