<link rel="stylesheet" href="<?= $this->getUrl('dist/bootstrap/css/bootstrap.min.css') ?>">
<!-- iCheck -->
<link rel="stylesheet" href="<?= $this->getUrl('dist/plugins/iCheck/square/blue.css') ?>">
<!-- Font Awesome -->
<link rel="stylesheet" href="<?= $this->getUrl('dist/font-awesome/css/font-awesome.min.css') ?>">
<!-- Ionicons -->
<link rel="stylesheet" href="<?= $this->getUrl('dist/Ionicons/css/ionicons.min.css') ?>">
<link rel="stylesheet" href="<?= $this->getUrl('dist/plugins/pace/pace.min.css') ?>">
<link rel="stylesheet" href="<?= $this->getUrl('dist/plugins/select2/css/select2.min.css') ?>">
<link rel="stylesheet" href="<?= $this->getUrl('dist/zf-table/css/zf-table.css') ?>">
<!-- Theme style -->
<link rel="stylesheet" href="<?= $this->getUrl('dist/css/AdminLTE.min.css') ?>">
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
      page. However, you can choose any other skin. Make sure you
      apply the skin class to the body tag so the changes take effect. -->
<link rel="stylesheet" href="<?= $this->getUrl('dist/css/skins/_all-skins.min.css') ?>">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<!--        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">-->

<!-- jQuery 3 -->
<script src="<?= $this->getUrl('dist/jquery/jquery.min.js') ?>"></script>
<script src="<?= $this->getUrl('dist/zf-table/js/zf-table.js') ?>"></script>