<?php if ($pageCount): ?>
    <ul class="pagination">
        <li <?php echo!isset($previous) ? 'class="disabled"' : ''; ?>>
            <a data-page="<?php echo $first?>" href="">&laquo;</a></li>
        <li <?php echo!isset($previous) ? 'class="disabled"' : ''; ?>>
            <a data-page="<?php echo $previous?>" href="">&lsaquo;</a></li>

        <!-- Numbered page links -->
        <?php foreach ($pagesInRange as $page): ?>
            <li <?php echo $page == $current ? 'class="active"' : ''; ?>>
                <a data-page="<?php echo $page?>" href="">
                    <?php echo $page; ?>
                </a>
            </li>
        <?php endforeach; ?>
        <!-- Next page link -->
        <li <?php echo!isset($next) ? 'class="disabled"' : ''; ?>>
            <a data-page="<?php echo $next?>" href="">&rsaquo;</a></li>
        <!-- Last page link -->
        <li <?php echo!isset($next) ? 'class="disabled"' : ''; ?>>
            <a data-page="<?php echo $last?>" href="">&raquo;</a></li>
    </ul>
<?php endif; ?>
