<div class="modal fade" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            
            <div class="modal-body">  
          
                  Exemplo Modal
               
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary">Adicionar produto</button>
            </div>
           
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
