  
<!-- Content Header (Page header) -->
    <?= $this->partials("top-navigation",[
        'a'=>"Admin",'b'=>"Lista de privilégios",'c'=>"Listar", "d"=>'privilegios']); ?>
      <!-- Main content -->
      <section class="content">
      	<div id="tableContainer"></div>
<script>
    $(function () {
        $("#tableContainer").zfTable('<?= $this->route->pathFor('api.privilegios') ?>');
    })
</script>
</section>