<?= $this->form->openTag($form); ?>
<?= $this->formRow($form->get('id'))->o() ?>
<?= $this->formRow($form->get('client')->setAttribute('value',$client))->o() ?>
<?= $this->formRow($form->get('empresa'))->o() ?>
<?= $this->formRow($form->get('name'))->i() ?>
<?= $this->formRow($form->get('street'))->i() ?>
<?= $this->formRow($form->get('created_at'))->i() ?>
<?= $this->formRow($form->get('updated_at'))->i() ?>
<div class="form-group">
    <div class="col-sm-offset-3 col-sm-6">
        <?=
        $this->formButton([
            'value' => 'Save',
            'type' => 'submit',
            'class' => 'btn btn-primary btn-block btn-flat'
        ])
        ?>
    </div>
    <div class="col-sm-3">
        <a href=" <?=
        $this->route->pathFor('client.edit', [
            'id' => $form->get('id')->getAttribute('value')
        ]);
        ?>" class="btn btn-danger btn-block btn-flat"><i class="fa fa-reply-all"></i> Voltar</a>
    </div>
</div>


<?= $this->form->closeTag(); ?>