<?php if($showButtonsActions):?>
<div class="mailbox-controls">
    <!-- Check all button -->
    <div class="btn-group">
        <form action="<?= $this->route->pathFor(sprintf("%s.create", $route)) ?>" name="ajaxForm" method="post" style="display: flex;float: left;">
            <button style="margin-left: 10px;" class="actions btn btn-success btn-sm btn-flat"><i class="fa fa-plus-circle"></i> <?=$valueButtonsActions['add']?></button>
        </form>
        <?php if ($valuesState != '1'): ?>
            <a  href="<?=
            $this->route->pathFor(sprintf("%s.state", $route), [
                'id' => '1'
            ])
            ?>" id="1" style="margin-left: 10px;" type="button" class="actions btn btn-warning btn-flat btn-sm"><i class="fa fa-check"></i> <?=$valueButtonsActions['active']?></a>
        <?php endif; ?>
        <?php if ($valuesState != '2'): ?>
            <a  href="<?=
                $this->route->pathFor(sprintf("%s.state", $route), [
                    'id' => '2'
                ])
                ?>" id="2" style="margin-left: 10px;" type="button" class="actions btn bg-gray btn-flat btn-sm"><i class="fa fa-close"></i> <?=$valueButtonsActions['inactive']?></a>
            <?php endif; ?>
            <?php if ($valuesState != '3'): ?>
            <a  href="<?=
            $this->route->pathFor(sprintf("%s.state", $route), [
                'id' => '3'
            ])
                ?>" id="3" style="margin-left: 10px;" type="button" class="actions btn bg-blue btn-flat btn-sm"><i class="fa fa-trash"></i> <?=$valueButtonsActions['trash']?></a>
        <?php endif; ?>
<?php if ($valuesState == '3'): ?>
            <a  href="<?= $this->route->pathFor(sprintf("%s.delete", $route)) ?>" id="4" style="margin-left: 10px;" type="button" class="actions btn btn-danger btn-flat btn-sm"><i class="fa fa-eraser"></i> <?=$valueButtonsActions['trashall']?></a>
        <?php endif; ?>
        <?php if ($showExportToCSV): ?>
            <a href="#" style="margin-left: 10px;" class="export-csv btn bg-aqua btn-flat btn-sm"><?=$valueButtonsActions['csv']?></a>
<?php endif; ?>
    </div>
    <!-- /.btn-group -->
    <div class="pull-right"  style="margin-right: 10px;">
<?= $firstItemNumber; ?>-<?= $lastItemNumber; ?>/<?= $totalItemCount; ?>
        <!-- /.btn-group -->
    </div>
    <!-- /.pull-right -->
</div>
<?php endif;?>