<div class="zf-table-wrap  form-inline">
    <div class="row">
        <div class="col-xs-12">
			<?= $this->partials('zf-table/box-top', $dataViews); ?>
			<?= $this->partials('zf-table/box-controls', ['dataViews'=>$dataViews]); ?>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
<?php extract($dataViews);?>
				<?php echo $table; ?>

            </div>
            <!-- /.box-body -->
			<?= $this->partials('zf-table/box-footer', $dataViews); ?>
        </div>
        <!-- /.box -->
    </div>
</div>
<?= $this->partials('zf-table/default-params',  ['dataViews'=>$dataViews]); ?>
</div>


<script>
    $(function () {
        $(".checkbox-toggle").click(function () {
            var clicks = $(this).data('clicks');
            if (clicks) {
                //Uncheck all checkboxes
                $(".table input[type='checkbox']").iCheck("uncheck");
                $(".fa", this).removeClass("fa-check-square-o").addClass('fa-square-o');
            } else {
                //Check all checkboxes
                $(".table input[type='checkbox']").iCheck("check");
                $(".fa", this).removeClass("fa-square-o").addClass('fa-check-square-o');
            }
            $(this).data("clicks", !clicks);
        });
    });
</script>