<div class="zf-table-wrap  form-inline">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <?php if ($name): ?>
                        <h3 class="box-title">
                            <?= $name ?>
                        </h3>
                    <?php endif; ?>
                <!-- /.box-header -->
                <div class="box-body table-responsive">
                    <?php echo $table; ?>
                </div>
                <!-- /.box-body -->

            </div>
            <!-- /.box -->
        </div>
    </div>

</div>