
  <header class="main-header">
    <nav class="navbar navbar-static-top">
      <div class="">
        <div class="navbar-header">
          <a href="<?=$this->route->pathFor('admin')?>" class="navbar-brand"><b>Admin</b>LTE</a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <i class="fa fa-bars"></i>
          </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
          <ul class="nav navbar-nav">
             <?php $defaul = $this->menu->getMenus('default',['dashboard', 'home-site', 'account', 'sair']); ?>
            <?php 
            if ($defaul): ?>               
                <?php foreach ($defaul as $treview): ?>
                    <?php
                    if (isset($treview['pages'])):?>
                        <li class="dropdown <?= $this->menu->active($treview['route']) ?>">
                             <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="<?= $treview['icone']?>"></i> &nbsp;&nbsp; <?= $treview['label'] ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                               <?php
                                foreach ($treview['pages'] as $treview_menu):?>
                                <li><a href="<?=$this->route->pathFor($treview_menu['route'])?>"><i class="<?= $treview_menu['icone']?>"></i> <?= $treview_menu['label']?></a></li>
                                  <?php endforeach;
                                ?>
                            </ul>
                        </li>
                    <?php else: ?>
                        <li class="<?= $this->menu->active($treview['route']) ?>"><a href="<?= $this->route->pathFor($treview['route']) ?>"><i class="<?= $treview['icone']?>"></i>  &nbsp;&nbsp;<?= $treview['label'] ?> <span class="sr-only">(current)</span></a></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
           </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" id="navbar-search-input" placeholder="Search">
            </div>
          </form>
        </div>
        <!-- /.navbar-collapse -->
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            <!-- Messages: style can be found in dropdown.less-->

            <!-- /.messages-menu -->
            <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="<?= $this->getUrl($user['cover'])?>" class="user-image" alt="<?=$user['first_name'];?>">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs"> <?=$user['first_name']?> <?=$user['last_name'];?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="<?= $this->getUrl($user['cover'])?>" class="img-circle" alt="<?=$user['first_name']?>">

                            <p>
                                <?=$user['first_name']?> <?=$user['last_name'];?> - Web Developer
                                <small>Desde:  <?= date("d/m/Y", strtotime($user['created_at']))?></small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="row">

                            </div>
                            <!-- /.row -->
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="<?=$this->route->pathFor('usuario.profile')?>" class="btn btn-default btn-flat">Minha Conta</a>
                            </div>
                            <div class="pull-right">
                                <a href="<?=$this->route->pathFor('usuario.logout')?>" class="btn btn-default btn-flat">Sair</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
           
          </ul>
        </div>
        <!-- /.navbar-custom-menu -->
      </div>
      <!-- /.container-fluid -->
    </nav>
  </header>