<div class="zf-table-wrap  form-inline">
    <div class="row">
        <div class="col-xs-12">

				<?= $this->partials('zf-table/box-top', $paginator); ?>
				<?= $this->partials('box-controls', $paginator); ?>
                <!-- /.box-header -->
                <div class="box-body table-responsive">
					<?php if($data):
						d($data);
					endif;?>

                </div>
                <!-- /.box-body -->
			<?= $this->partials('zf-table/box-footer', $paginator); ?>
            </div>
            <!-- /.box -->
        </div>
    </div>
	<?= $this->partials('default-params', $paramsWrap); ?>
</div>