<!-- Profile Image -->
              <div class="box-body box-profile">
              <img id="attachment" class="img-responsive" src="<?= $this->getUrl($data_cover) ?>" alt="<?= $title ?>">

              <h3 class="profile-username text-center"><?= $title ?></h3>
             <div class="form-group">
                <div class="btn btn-default btn-file btn-block">
                  <i class="fa fa-paperclip"></i> Selecione Imagem
                  <input name="attachment" type="file">
                </div>
                <p class="help-block">Max. 32MB</p>
              </div>
            </div>