<?php
$name = $field->getName();
if ($name === null || $name === '') {
    throw new \Exception(sprintf(
        '%s requires that the element has an assigned name; none discovered', __METHOD__
    ));
}
$attributes = $field->getAttributes();
$attributes['name'] = $name;
$attributes['type'] = $field->getType();
if (isset($attributes['value'])):
    $attributes['value'] = $attributes['value'];
    if (isset($attributes['pad_length'])):
        $attributes['value'] = str_pad($attributes['value'],
            $attributes['pad_length']['pad_length'],
            $attributes['pad_length']['pad_string'],
            $attributes['pad_length']['pad_type']);
        if ('password' == $attributes['type']) {
            $attributes['value'] = '';
        }
        unset($attributes['pad_length']);
    endif;
    if ('password' == $attributes['type']) {
        $attributes['value'] = '';
    }
endif;

?>
<div class="form-group">
    <label for="<?= $field->getId() ?>"><?= $field->getLabel() ?></label>
    <?=sprintf('<input %s>', $this->formRow->createAttributesString($attributes)); ?>
</div>