<?php
$name = $field->getName();
if ($name === null || $name === '') {
    throw new \Exception(sprintf(
            '%s requires that the element has an assigned name; none discovered', __METHOD__
    ));
}
$attributes = $field->getAttributes();
$attributes['name'] = $name;
$attributes['type'] = "hidden";
if (isset($attributes['value'])):
    $attributes['value'] = $attributes['value'];
endif;
?>
<?=sprintf('<input %s>', $this->formRow->createAttributesString($attributes)); ?>