<?php
$name = $field->getName();
if ($name === null || $name === '') {
    throw new \Exception(sprintf(
            '%s requires that the element has an assigned name; none discovered', __METHOD__
    ));
}
$attributes = $field->getAttributes();
$attributes['name'] = $name;
$attributes['type'] = $field->getType();
if (isset($attributes['value'])):
    $attributes['value'] = $attributes['value'];
    if ('password' == $attributes['type']) {
        $attributes['value'] = '';
    }
endif;
?>
<div class="form-group">
<div class="input-group">
 <?=sprintf('<input %s>', $this->formRow->createAttributesString($attributes)); ?>
    <span class="input-group-btn">
      <button type="button" class="btn btn-info btn-flat"><?=$t?></button>
    </span>
</div>
</div>