<?php

$name = $field->getName();
if ($name === null || $name === '') {
    throw new \Exception(sprintf(
            '%s requires that the element has an assigned name; none discovered', __METHOD__
    ));
}
$attributes = $field->getAttributes();
$attributes['name'] = $name;

if (!isset($attributes['value'])):
    $attributes['value'] = '';
endif;
$empty = "";
if (isset($options['value_options'])):
    $attributes['value_options'] = $options['value_options'];
endif;
if (isset($attributes['empty'])):
    $empty = sprintf("<option value=''>%s</option>", $attributes['empty']);
endif;

$options = $this->formRow->getValuesOptions($attributes);
unset($attributes['value'], $attributes['label'], $attributes['placeholder'], $attributes['empty']);

?>
<div class="form-group">
    <label for="<?= $field->getId() ?>"><?= $field->getLabel() ?></label>
    <?= sprintf('<select %s>%s%s</select>', $this->formRow->createAttributesString($attributes), $empty, $options); ?>
</div>
