<?php extract($dataViews);?>
<?php extract($dataViews['paramsWrap']);?>
<div class="params-wrap">
    <input type="hidden"  name="zfTablePage" value="<?php echo $page?>" />
    <input type="hidden"  name="zfTableColumn" value="<?php echo $column?>" />
    <input type="hidden"  name="zfTableOrder" value="<?php echo $order?>" />
    <input type="hidden"  name="zfTableQuickSearch" value="<?php echo $quickSearch?>" />
    <input type="hidden"  name="zfTableItemPerPage" value="<?php echo $itemCountPerPage?>" />
    <input type="hidden"  name="valuesState" value="<?php echo $valuesState?>" />
</div>
