<!-- Content Header (Page header) -->
    <?= $this->partials("top-navigation",[
        'a'=>"Admin",'b'=>"Usuario",'c'=>"Editar", "d"=>'usuario']); ?>
      <!-- Main content -->
      <section class="content">
        <div class="row">
    <div class="col-md-12">
        <!-- Custom Tabs (Pulled to the right) -->
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab_1-1" data-toggle="tab">Geral</a></li>
                <li><a href="#address" data-toggle="tab">Endereço</a></li>
                <li class="pull-right header"><i class="fa fa-th"></i> Manutenção do usuario</li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab_1-1">
                    <?= $this->form->openTag($form); ?>
                    <div class="col-md-9">
                         <?= $this->form->openTag($form); ?>
                        <?= $this->partials('form/hidden', ['field' => $form->get('id')]) ?>
                        <?= $this->partials('form/input', ['field' => $form->get('first_name')]) ?>
                        <?= $this->partials('form/input', ['field' => $form->get('last_name')]) ?>
                        <?= $this->partials('form/input', ['field' => $form->get('email')]) ?>
                        <?= $this->partials('form/input', ['field' => $form->get('password')]) ?>
                        <?php if($user['role']=="admin"):?>
                        <?= $this->partials('form/select', ['field' => $form->get('role')]) ?>
                    <?php else:?>
                        <?= $this->partials('form/hidden', ['field' => $form->get('role')]) ?>
                    <?php endif;?>
                        <?= $this->partials('form/input', ['field' => $form->get('created_at')]) ?>
                        <?= $this->partials('form/input', ['field' => $form->get('updated_at')]) ?>
                    </div>
                    <div class="col-md-3">
                        <?=
                        $this->partials('form/file', [
                            'data_cover' => $form->get('cover')->getAttribute('value'),
                            'title' => $form->get('first_name')->getAttribute('value')
                        ])
                        ?>       
                        <!-- /.box -->
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-6">
                            <?=
                            $this->partials('form/button', [
                                'value' => 'Atualizar Dados Do Usuario',
                                'type' => 'submit',
                                'class' => 'btn btn-primary btn-block btn-flat'
                            ])
                            ?>
                        </div>
                        <div class="col-sm-3">
                            <a href=" <?= $this->route->pathFor('usuario'); ?>" class="btn btn-danger btn-block btn-flat"><i class="fa fa-reply-all"></i> Voltar</a>
                        </div>
                    </div>
                    <?= $this->form->closeTag(); ?>
                    <div class="clearfix"></div>

                </div>
                <!-- /.tab-pane -->
                <div class="tab-pane" id="address">
                   endereço
                </div>
                <!-- /.tab-pane -->
            </div>
            <!-- /.tab-content -->
        </div>
        <!-- nav-tabs-custom -->
    </div>
    <!-- /.col -->
</div>
</section>