<!-- Content Header (Page header) -->
    <?= $this->partials("top-navigation",[
        'a'=>"Admin",'b'=>"Usuario",'c'=>"Minha Conta", "d"=>'usuario']); ?>
      <!-- Main content -->
      <section class="content">
    <div class="row">
        <div class="col-md-3">

            <!-- Profile Image -->
            <div class="box box-primary">
                <div class="box-body box-profile">
                    <img id="attachment" data-cover="<?= $this->getUrl($data['cover']); ?>" class="img-responsive" src="<?= $this->getUrl($data['cover']); ?>" alt="<?= $data['first_name'] ?>">

                    <h3 class="profile-username text-center"><?= $data['first_name'] ?> <?= $data['last_name'] ?></h3>

                    <p class="text-muted text-center"><?= $data['role'] ?></p>

                    <ul class="list-group list-group-unbordered">
                        <li class="list-group-item">
                            <b>E-Mail</b> <a class="pull-right"><?= $data['email'] ?></a>
                        </li>
                    </ul>
                    <?= $this->form->openTag($form); ?>

                    <div class="form-group">
                        <?= $this->partials('form/hidden', ['field' => $form->get('id')]) ?>
                        <?= $this->partials('form/hidden', ['field' => $form->get('first_name')]) ?>
                        <?= $this->partials('form/hidden', ['field' => $form->get('last_name')]) ?>
                        <?= $this->partials('form/hidden', ['field' => $form->get('email')]) ?>
                        <div class="btn btn-default btn-file btn-block">
                            <i class="fa fa-paperclip"></i> Selecionar Foto
                            <input name="attachment" type="file">
                        </div>
                    </div>
                    <button class="btn btn-primary btn-block"><b>Atualizar</b></button>
                    <?= $this->form->closeTag(); ?>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

            <!-- About Me Box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Sobre mim</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <strong><i class="fa fa-book margin-r-5"></i> Education</strong>

                    <p class="text-muted">
                        B.S. in Computer Science from the University of Tennessee at Knoxville
                    </p>

                    <hr>

                    <strong><i class="fa fa-map-marker margin-r-5"></i> Location</strong>

                    <p class="text-muted">Malibu, California</p>

                    <hr>

                    <strong><i class="fa fa-pencil margin-r-5"></i> Skills</strong>

                    <p>
                        <span class="label label-danger">UI Design</span>
                        <span class="label label-success">Coding</span>
                        <span class="label label-info">Javascript</span>
                        <span class="label label-warning">PHP</span>
                        <span class="label label-primary">Node.js</span>
                    </p>

                    <hr>

                    <strong><i class="fa fa-file-text-o margin-r-5"></i> Notes</strong>

                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#settings" data-toggle="tab" aria-expanded="false">Settings</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="settings">
                        <?= $this->form->openTag($form); ?>
                        <?= $this->partials('form/hidden', ['field' => $form->get('id')]) ?>
                        <?= $this->partials('form/input', ['field' => $form->get('first_name')]) ?>
                        <?= $this->partials('form/input', ['field' => $form->get('last_name')]) ?>
                        <?= $this->partials('form/input', ['field' => $form->get('email')->setAttribute('readonly',true)]) ?>
                        <?= $this->partials('form/input', ['field' => $form->get('password')]) ?>
                        <?= $this->partials('form/input', ['field' => $form->get('created_at')]) ?>
                        <?= $this->partials('form/input', ['field' => $form->get('updated_at')]) ?>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <?=
                                $this->partials('form/button', [
                                    'value' => 'Atualizar Meus Dados',
                                    'type' => 'submit',
                                    'class' => 'btn btn-primary btn-block btn-flat'
                                ])
                                ?>
                            </div>
                        </div>
                        <?= $this->form->closeTag(); ?>
                    </div>
                    <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
            </div>
            <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

</section>