<!-- Content Header (Page header) -->
<?=
$this->partials("top-navigation", [
    'a' => "Admin", 'b' => "Tabela", 'c' => "Editar", "d" => 'admin']);
?>
<!-- Main content -->
<section class="content">
    <div class="row">
    <div class="col-md-12">
        <!-- Custom Tabs (Pulled to the right) -->
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab-1" data-toggle="tab">Tabela</a></li>
                <li class="pull-right header"><i class="fa fa-th"></i> Manutenção do Tabela</li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab-1">
                    <?= $this->form->openTag($form); ?>
                    <div class="col-md-12">
                        <?=
                        $this->partials('form/form-group-textarea', ['field' => $form->get('file')])
                        ?>       
                        <!-- /.box -->
                    </div>
                    <div class="form-group">
                        <div class="col-sm-8">
                            <?=
                            $this->partials('form/button', [
                                'value' => 'Atualizar Dados Do Tabela',
                                'type' => 'submit',
                                'class' => 'btn btn-primary btn-block btn-flat'
                            ])
                            ?>
                        </div>
                        <div class="col-sm-4">
                            <a href=" <?= $this->route->pathFor('admin'); ?>" class="btn btn-danger btn-block btn-flat"><i class="fa fa-reply-all"></i> Voltar</a>
                        </div>
                    </div>
                    <?= $this->form->closeTag(); ?>
                    <div class="clearfix"></div>

                </div>
                <!-- /.tab-pane -->
                 </div>
            <!-- /.tab-content -->
        </div>
        <!-- nav-tabs-custom -->
    </div>
    <!-- /.col -->
</div>
</section>