<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>AdminLTE 2 | Log in</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="<?= $this->getUrl('dist/bootstrap/css/bootstrap.min.css') ?>">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="<?= $this->getUrl('dist/font-awesome/css/font-awesome.min.css'); ?>">
        <!-- Ionicons -->
        <link rel="stylesheet" href="<?= $this->getUrl('dist/Ionicons/css/ionicons.min.css'); ?>">
        <!-- Theme style -->
        <link rel="stylesheet" href="<?= $this->getUrl('dist/css/AdminLTE.min.css') ?>">
        <!-- iCheck -->
        <link rel="stylesheet" href="<?= $this->getUrl('dist/plugins/iCheck/square/blue.css') ?>">
        <link rel="stylesheet" href="<?= $this->getUrl('dist/plugins/jquery-confirm/jquery-confirm.min.css') ?>">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
            .login-page{
                background: #7dcfab url(<?= $this->getUrl('dist/img/fundo3.jpg') ?>);
                background-attachment: fixed;
                background-repeat: no-repeat;
                background-size: 100%;
            }
            

        </style>
        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    </head>
    <body class="hold-transition login-page">
        <?= $this->content(); ?>
        <!-- /.login-box -->

        <!-- jQuery 3 -->
        <script src="<?= $this->getUrl('dist/jquery/jquery.min.js') ?>"></script>
        <!-- Bootstrap 3.3.7 -->
        <script src="<?= $this->getUrl('dist/bootstrap/js/bootstrap.min.js') ?>"></script>
        <script src="<?= $this->getUrl('dist/js/jquery.form.min.js') ?>"></script>
        <!-- iCheck -->
        <script src="<?= $this->getUrl('dist/plugins/iCheck/icheck.min.js') ?>"></script>
        <script src="<?= $this->getUrl('dist/plugins/jquery-confirm/jquery-confirm.min.js') ?>"></script>
        <script src="<?= $this->getUrl('dist/js/bootstrap-notify.min.js') ?>"></script>
        <script src="<?= $this->getUrl('dist/js/auth.js') ?>"></script>
        <script>
            $(function () {
                $('input').iCheck({
                    checkboxClass: 'icheckbox_square-blue',
                    radioClass: 'iradio_square-blue',
                    increaseArea: '20%' // optional
                });
            });
        </script>
    </body>
</html>